---
- hosts: localhost

  vars:
    tools:
      - caffeine
      #- docker-engine
      - geary
      - default-jdk
      - libpq-dev
      - mongodb
      - nmap
      - nodejs
      - npm
      - openssl
      - phantomjs
      - pkg-config
      - postgresql
      - python3
      - sqlite
      - tig
      - tmux
      - vim
      - virtualbox
      - vlc
      - zsh
    dotfiles_dir: /home/dgliwa/dotfiles
    email: dgliwa7bhs@gmail.com
    github_username: dgliwa
    home_dir: /home/dgliwa
    name: Derek Gliwa
    zsh_path: /usr/bin/zsh

  tasks:
    - include: tasks/apt-repos.yml
      tags: [apt]
      sudo: yes
    - include: tasks/apt-install.yml
      tags: [apt]
      sudo: yes
    - include: tasks/install-rvm.yml
      tags: [rvm]
    - include: tasks/zsh.yml
      tags: [zsh]
    - include: tasks/dotfiles.yml
      tags: [dotfiles]
    - include: tasks/gitconfig.yml
      tags: [gitconfig]
