- name: Install apt libraries
  apt: name={{ item }} state=present
  with_items: '{{tools}}'

- name: Install slack
  apt:
    deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-2.3.3-amd64.deb

- name: Install ack
  apt: 
    deb: http://security.ubuntu.com/ubuntu/pool/universe/a/ack/ack_1.39-12_amd64.deb


