---
- name: Check out dotfiles repo
  git:
    repo: git@github.com:dgliwa/dotfiles.git
    dest: "{{ dotfiles_dir }}"
    accept_hostkey: yes

- name: Apply dotfiles
  shell: rcup -f -d {{ dotfiles_dir }}

- name: Install vim plugins
  shell: vim +PluginInstall +qall
