---
- name: Determine if zsh is default/current shell
  shell: echo $SHELL
  register: current_shell

- name: Enable zsh in /etc/shells
  shell: sudo /bin/sh -c 'grep -q "{{ zsh_path }}" /etc/shells || echo "{{ zsh_path }}" >> /etc/shells'
  when: current_shell.stdout != '{{ zsh_path }}'

- name: Set zsh as default shell
  shell: chsh -s {{ zsh_path }}
  when: current_shell.stdout != '{{ zsh_path }}'

